version = 1

[[annotations]]
path = ["**.h", "**.cpp"]
SPDX-FileCopyrightText = "2026 John McKenzie"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["**.md", "**.toml", "**.yml", "**.yaml", "**.json", "**.ini", "**.txt", "**.cmake"]
SPDX-FileCopyrightText = "2026 John McKenzie"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".gitignore", ".gitattributes", ".editorconfig", ".clang-format", ".clangd", ".github/CODEOWNERS"]
SPDX-FileCopyrightText = "2026 John McKenzie"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".vscode/**"]
SPDX-FileCopyrightText = "2026 John McKenzie"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["scripts/**"]
SPDX-FileCopyrightText = "2026 John McKenzie"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "LICENSES/**"
SPDX-FileCopyrightText = "Free Software Foundation, Inc."
SPDX-License-Identifier = "LicenseRef-scancode-public-domain"
