// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include <cstdint>
#include <span>

namespace fl {

// Minimal glTF 2.0 binary (.glb) meshes embedded as byte arrays.
// Generated by tools/gen_builtin_glb.py; uploaded via IRenderer::createMesh.
//
// kTetrahedronGlb — regular tetrahedron, ~10 m circumradius, +X forward.
//   4 triangular faces, 12 vertices with per-face normals (POSITION + NORMAL).
//   Used as a placeholder mesh for entities when no content pack provides one.
//
// kFloorPlaneGlb — flat 4 km × 4 km quad at Y=0, normal (0,1,0).
//   4 vertices, 6 indices. Used as the builtin sandbox floor plane.

std::span<const uint8_t> builtinTetrahedronGlb() noexcept;
std::span<const uint8_t> builtinFloorPlaneGlb() noexcept;

} // namespace fl
